# Generated by Django 3.2 on 2021-04-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('number', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('mazda', 'mazda'), ('mers', 'mers')], max_length=30)),
                ('dosier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dosier')),
            ],
        ),
    ]
