# Generated by Django 3.2 on 2021-04-28 13:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dosier',
            new_name='Dossier',
        ),
    ]
