# Generated by Django 3.2 on 2021-04-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_dosier_dossier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='dosier',
            new_name='dossier',
        ),
    ]
