# Generated by Django 3.2 on 2021-05-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_dosier_car_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Warcrart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('military_area', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('start_pose', models.DateField(auto_now_add=True)),
                ('end_pose', models.DateField()),
                ('dossier', models.ManyToManyField(to='accounts.Dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('school_name', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('dossier', models.ManyToManyField(to='accounts.Dossier')),
            ],
        ),
    ]
