# Generated by Django 3.2 on 2021-05-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210505_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='dossier',
        ),
        migrations.AddField(
            model_name='education',
            name='dossier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.dossier'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='warcrart',
            name='dossier',
        ),
        migrations.AddField(
            model_name='warcrart',
            name='dossier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.dossier'),
            preserve_default=False,
        ),
    ]
