# Generated by Django 3.2 on 2021-05-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210505_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warcraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('military_area', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('start_pose', models.DateField(auto_now_add=True)),
                ('end_pose', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='education',
            name='dossier',
        ),
        migrations.DeleteModel(
            name='Warcrart',
        ),
    ]
