# Generated by Django 3.2 on 2021-05-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210505_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='accounts.dossier'),
        ),
        migrations.AlterField(
            model_name='education',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.dossier'),
        ),
        migrations.AlterField(
            model_name='warcraft',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warcraft', to='accounts.dossier'),
        ),
    ]
