# Generated by Django 3.2 on 2021-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now=True)),
                ('date_expired', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('dead', 'dead')], max_length=30)),
                ('document_root', models.CharField(max_length=30)),
            ],
        ),
    ]
