# Generated by Django 3.2 on 2021-04-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_root',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('secret', 'secret'), ('top-secret', 'top-secret')], max_length=30),
        ),
    ]
