# Generated by Django 3.2 on 2021-04-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0002_alter_document_document_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
