# Generated by Django 3.2 on 2021-05-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0003_alter_document_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('dead', 'dead')], default='active', max_length=30),
        ),
    ]
